
\SweaveOpts{fig.path='figs/navigation-', fig.align='center',
  fig.show='hold', tidy=FALSE, prompt=TRUE, comment=''}


\progrchapter{Navigation}
\progrsectionabstract{
  Navigate through R; first steps in finding, reading, debugging,
  etc. R objects.
}








%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Environments}

<<>>=
globalenv()
ls(envir = globalenv())
@

<<>>=

@




